import { useParams, useNavigate } from "react-router-dom";
import Sidebar from "../components/Sidebar";
import { useState } from "react";
import { useAuth } from "../context/AuthContext";

function ClaimDetails() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { user } = useAuth();
  const role = user?.role;

  const claim = {
    id,
    customer: "Isuru Fernando",
    contact: "077-1234567",
    vehicle: "Toyota Hilux",
    plate: "CAB-2345",
    year: 2019,
    status: "Pending",
    ml: {
      estimate: 210000,
      confidence: 82,
      damages: ["Front bumper", "Left door", "Headlamp"],
    },
    images: [
      "https://via.placeholder.com/300x200?text=Damage+1",
      "https://via.placeholder.com/300x200?text=Damage+2",
      "https://via.placeholder.com/300x200?text=Damage+3",
    ],
    history: [
      { status: "Submitted", by: "Customer", date: "2026-02-10 09:14" },
      { status: "AI Estimate Generated", by: "AVA AI", date: "2026-02-10 09:15" },
      { status: "Pending", by: "System", date: "2026-02-10 09:15" },
    ],
  };

  const [status, setStatus] = useState(claim.status);
  const [estimate, setEstimate] = useState(claim.ml.estimate);
  const [history, setHistory] = useState(claim.history);

  const updateStatus = (newStatus) => {
    setStatus(newStatus);
    setHistory([
      ...history,
      { status: newStatus, by: "Agent", date: new Date().toLocaleString() },
    ]);
  };

  return (
    <div style={styles.layout}>
      <Sidebar />

      <main style={styles.content}>
        <div style={styles.container}>
          <button style={styles.backBtn} onClick={() => navigate(-1)}>
            ← Back to Claims
          </button>

          <h1 style={styles.heading}>Claim #{claim.id}</h1>

          <p style={{ marginBottom: "20px", opacity: 0.8 }}>
            Role: <b>{role}</b>
          </p>

          {/* INFO */}
          <div style={styles.cards}>
            <Card title="Customer Details">
              <p><b>Name:</b> {claim.customer}</p>
              <p><b>Contact:</b> {claim.contact}</p>
            </Card>

            <Card title="Vehicle Details">
              <p><b>Vehicle:</b> {claim.vehicle}</p>
              <p><b>Plate:</b> {claim.plate}</p>
              <p><b>Year:</b> {claim.year}</p>
            </Card>
          </div>

          {/* ML */}
          <Section title="Estimated Cost Generated by AI">
            <input
              type="number"
              value={estimate}
              disabled={role === "viewer"}
              onChange={(e) => setEstimate(e.target.value)}
              style={{
                ...styles.input,
                background: role === "viewer" ? "#ccc" : "#fff",
                cursor: role === "viewer" ? "not-allowed" : "text",
              }}
            />

            <p style={{ marginTop: "8px" }}>
              Confidence: <b>{claim.ml.confidence}%</b>
            </p>

            <ul>
              {claim.ml.damages.map((d, i) => (
                <li key={i}>{d}</li>
              ))}
            </ul>
          </Section>

          {/* TIMELINE */}
          <Section title="Claim Timeline">
            <div style={styles.timeline}>
              {history.map((h, i) => (
                <div key={i} style={styles.timelineItem}>
                  <div style={styles.timelineDot} />
                  <div>
                    <b>{h.status}</b>
                    <div style={styles.timelineMeta}>
                      {h.by} • {h.date}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </Section>

          {/* ACTIONS */}
          {role !== "viewer" && (
            <div style={styles.actions}>
              <button style={styles.approve} onClick={() => updateStatus("Approved")}>
                Approve
              </button>
              <button style={styles.review} onClick={() => updateStatus("Under Review")}>
                Under Review
              </button>
              <button style={styles.reject} onClick={() => updateStatus("Rejected")}>
                Reject
              </button>
            </div>
          )}

          <p style={styles.status}>
            Current Status: <b>{status}</b>
          </p>
        </div>
      </main>
    </div>
  );
}

function Card({ title, children }) {
  return (
    <div style={styles.card}>
      <h3>{title}</h3>
      {children}
    </div>
  );
}

function Section({ title, children }) {
  return (
    <div style={styles.section}>
      <h3>{title}</h3>
      {children}
    </div>
  );
}

const styles = {
  layout: { display: "flex", minHeight: "100vh" },
  content: {
    flex: 1,
    marginLeft: "220px",
    padding: "30px",
    background: "linear-gradient(135deg, #0f2027, #203a43, #2c5364)",
  },
  container: { maxWidth: "1100px", margin: "0 auto", color: "#fff" },
  backBtn: { background: "none", border: "none", color: "#00e0ff", cursor: "pointer" },
  heading: { fontSize: "30px", marginBottom: "10px" },
  cards: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "20px" },
  card: { background: "#2a536b", padding: "20px", borderRadius: "16px" },
  section: { marginTop: "30px" },
  input: { padding: "10px", borderRadius: "8px", border: "none", width: "220px" },
  timeline: { marginTop: "15px", borderLeft: "3px solid #00e0ff", paddingLeft: "20px" },
  timelineItem: { marginBottom: "14px", position: "relative" },
  timelineDot: { position: "absolute", left: "-11px", top: "6px", width: "10px", height: "10px", background: "#00e0ff", borderRadius: "50%" },
  timelineMeta: { fontSize: "12px", opacity: 0.8 },
  actions: { marginTop: "30px", display: "flex", gap: "15px" },
  approve: { background: "#27ae60", color: "#fff", padding: "10px 20px", border: "none", borderRadius: "8px" },
  review: { background: "#f39c12", color: "#fff", padding: "10px 20px", border: "none", borderRadius: "8px" },
  reject: { background: "#c0392b", color: "#fff", padding: "10px 20px", border: "none", borderRadius: "8px" },
  status: { marginTop: "20px", fontSize: "16px" },
};

export default ClaimDetails;